---
inventory:
    plugin: SimpleInventory
    options:
        host_file: "./inventory/hosts.yaml"
        group_file: "./inventory/groups.yaml"
        defaults_file: "./inventory/defaults.yaml"

logging:
    enabled: True
    log_file: "./log/nornir.log"

runner:
    plugin: threaded
    options:
        num_workers: 20
...